@echo off
title Activate Windows 10 ALL versions for FREE!&cls&echo ============================================================================&echo #Project: Activating Microsoft software products for FREE without software&echo ============================================================================&echo.&echo #Supported products:&echo - Windows 10 Home&echo - Windows 10 Home N&echo - Windows 10 Home Single Language&echo - Windows 10 Home Country Specific&echo - Windows 10 Professional&echo - Windows 10 Professional N&echo - Windows 10 Education&echo - Windows 10 Education N&echo - Windows 10 Enterprise&echo - Windows 10 Enterprise N&echo - Windows 10 Enterprise LTSB&echo - Windows 10 Enterprise LTSB N&echo.&echo.&echo ============================================================================&echo Activating your Windows...&cscript //nologo slmgr.vbs /ckms >nul&cscript //nologo slmgr.vbs /upk >nul&cscript //nologo slmgr.vbs /cpky >nul&set i=1&wmic os | findstr /I "enterprise" >nul
if %errorlevel% EQU 0 (cscript //nologo slmgr.vbs /ipk NPPR9-FWDCX-D2C8J-H872K-2YT43 >nul&cscript //nologo slmgr.vbs /ipk DPH2V-TTNVB-4X9Q3-TJR4H-KHJW4 >nul&cscript //nologo slmgr.vbs /ipk WNMTR-4C88C-JK8YV-HQ7T2-76DF9 >nul&cscript //nologo slmgr.vbs /ipk 2F77B-TNFGY-69QQF-B8YKP-D69TJ >nul&cscript //nologo slmgr.vbs /ipk DCPHK-NFMTC-H88MJ-PFHPY-QJ4BJ >nul&cscript //nologo slmgr.vbs /ipk QFFDN-GRT3P-VKWWX-X7T3R-8B639 >nul&cscript //nologo slmgr.vbs /ipk YNMGQ-8RYV3-4PGQ3-C8XTP-7CFBY >nul&cscript //nologo slmgr.vbs /ipk 8PTT6-RNW4C-6V7J2-C2D3X-MHBPB >nul&cscript //nologo slmgr.vbs /ipk WNMTR-4C88C-JK8YV-HQ7T2-76DF9 >nul&cscript //nologo slmgr.vbs /ipk 2F77B-TNFGY-69QQF-B8YKP-D69TJ >nul&cscript //nologo slmgr.vbs /ipk YYVX9-NTFWV-6MDM3-9PT4T-4M68B >nul&cscript //nologo slmgr.vbs /ipk WKDNC-X7KYJ-DMJMV-JBHPB-R6YK7 >nul&cscript //nologo slmgr.vbs /ipk QNVD9-6RJ3T-HHQGX-JK2CP-CKCHH >nul&cscript //nologo slmgr.vbs /ipk DHHQN-VPX2K-X4DX3-PGM9M-2PQDV >nul&cscript //nologo slmgr.vbs /ipk BNRMV-C6K9C-49T7H-YM2RR-3DBK7 >nul&cscript //nologo slmgr.vbs /ipk BT79Q-G7N6G-PGBYW-4YWX6-6F4BT >nul&cscript //nologo slmgr.vbs /ipk YTMG3-N6DKC-DKB77-7M9GH-8HVX7 >nul&goto server) else wmic os | findstr /I "home" >nul
if %errorlevel% EQU 0 (cscript //nologo slmgr.vbs /ipk TX9XD-98N7V-6WMQ6-BX7FG-H8Q99 >nul&cscript //nologo slmgr.vbs /ipk 3KHY7-WNT83-DGQKR-F7HPR-844BM >nul&cscript //nologo slmgr.vbs /ipk 7HNRX-D7KGG-3K4RQ-4WPJ4-YTDFH >nul&cscript //nologo slmgr.vbs /ipk PVMJN-6DFY6-9CCP6-7BKTT-D3WVR >nul&cscript //nologo slmgr.vbs /ipk DCPHK-NFMTC-H88MJ-PFHPY-QJ4BJ >nul&cscript //nologo slmgr.vbs /ipk XGVPP-NMH47-7TTHJ-W3FW7-8HV2C >nul&cscript //nologo slmgr.vbs /ipk DCPHK-NFMTC-H88MJ-PFHPY-QJ4BJ >nul&cscript //nologo slmgr.vbs /ipk WYPNQ-8C467-V2W6J-TX4WX-WT2RQ >nul&cscript //nologo slmgr.vbs /ipk QFFDN-GRT3P-VKWWX-X7T3R-8B639 >nul&goto server) else wmic os | findstr /I "education" >nul
if %errorlevel% EQU 0 (cscript //nologo slmgr.vbs /ipk NW6C2-QMPVW-D7KKK-3GKT6-VCFB2 >nul&cscript //nologo slmgr.vbs /ipk 2WH4N-8QGBV-H22JP-CT43Q-MDWWJ >nul&cscript //nologo slmgr.vbs /ipk WNMTR-4C88C-JK8YV-HQ7T2-76DF9 >nul&cscript //nologo slmgr.vbs /ipk 44RPN-FTY23-9VTTB-MP9BX-T84FV >nul&cscript //nologo slmgr.vbs /ipk VK7JG-NPHTM-C97JM-9MPGT-3V66T >nul&cscript //nologo slmgr.vbs /ipk 2F77B-TNFGY-69QQF-B8YKP-D69TJ >nul&cscript //nologo slmgr.vbs /ipk YVWGF-BXNMC-HTQYQ-CPQ99-66QFC >nul&cscript //nologo slmgr.vbs /ipk MNHF7-PDX97-CF4PT-BHJBQ-8K8XG >nul&cscript //nologo slmgr.vbs /ipk GVNJP-8BJ7F-K4J4B-YWR27-9BT6T >nul&cscript //nologo slmgr.vbs /ipk YN4Y9-Y74T2-PPG47-CFD74-9W3GT >nul&cscript //nologo slmgr.vbs /ipk QN4P6-PWK22-G74BT-WY34D-YBH3B >nul&cscript //nologo slmgr.vbs /ipk JNQHG-VTDGF-3XPJG-9TKR6-Y98XM >nul&cscript //nologo slmgr.vbs /ipk VK7JG-NPHTM-C97JM-9MPGT-3V66T >nul&cscript //nologo slmgr.vbs /ipk 6P99N-YF42M-TPGBG-9VMJP-YKHCF >nul&cscript //nologo slmgr.vbs /ipk W269N-WFGWX-YVC9B-4J6C9-T83GX >nul&goto server) else wmic os | findstr /I "10 pro" >nul
if %errorlevel% EQU 0 (cscript //nologo slmgr.vbs /ipk W269N-WFGWX-YVC9B-4J6C9-T83GX >nul&cscript //nologo slmgr.vbs /ipk MH37W-N47XK-V7XM9-C7227-GCQG9 >nul&cscript //nologo slmgr.vbs /ipk NW6C2-QMPVW-D7KKK-3GKT6-VCFB2 >nul&cscript //nologo slmgr.vbs /ipk QFFDN-GRT3P-VKWWX-X7T3R-8B639 >nul&cscript //nologo slmgr.vbs /ipk NPPR9-FWDCX-D2C8J-H872K-2YT43 >nul&cscript //nologo slmgr.vbs /ipk 4CPRK-NM3K3-X6XXQ-RXX86-WXCHW >nul&cscript //nologo slmgr.vbs /ipk 84NGF-MHBT6-FXBX8-QWJK7-DRR8H >nul&cscript //nologo slmgr.vbs /ipk YTMG3-N6DKC-DKB77-7M9GH-8HVX7 >nul&cscript //nologo slmgr.vbs /ipk DXG7C-N36C4-C4HTG-X4T3X-2YV77 >nul&cscript //nologo slmgr.vbs /ipk WYPNQ-8C467-V2W6J-TX4WX-WT2RQ >nul&cscript //nologo slmgr.vbs /ipk DPH2V-TTNVB-4X9Q3-TJR4H-KHJW4 >nul&cscript //nologo slmgr.vbs /ipk 84NGF-MHBT6-FXBX8-QWJK7-DRR8H >nul&cscript //nologo slmgr.vbs /ipk RP7BT-XGNVB-X3DGW-JGT9R-7H644 >nul&cscript //nologo slmgr.vbs /ipk WN7YQ-FTFFX-R83HV-988M7-2R4CF >nul&cscript //nologo slmgr.vbs /ipk XPQYG-YPNPP-CYR6T-8V7RJ-DGPJR >nul&cscript //nologo slmgr.vbs /ipk CKFK9-QNGF2-D34FM-99QX2-8XC4K >nul&cscript //nologo slmgr.vbs /ipk PBHCJ-Q2NYD-2PX34-T2TD6-233PK >nul&cscript //nologo slmgr.vbs /ipk NPPR9-FWDCX-D2C8J-H872K-2YT43 >nul&goto server) else (goto notsupported)
:server
if %i%==1 set KMS=kms7.MSGuides.com
if %i%==2 set KMS=kms8.MSGuides.com
if %i%==3 set KMS=kms9.MSGuides.com
if %i%==4 goto notsupported
cscript //nologo slmgr.vbs /skms %KMS%:1688 >nul&echo ============================================================================&echo.&echo.
cscript //nologo slmgr.vbs /ato | find /i "successfully" && (echo.&echo ============================================================================&echo. if errorlevel 2 exit) || (echo The connection to my KMS server failed! Trying to connect to another one... & echo Please wait... & echo. & echo. & set /a i+=1 & goto server)
explorer "https://github.com/hoonsubin?tab=repositories"&goto halt
:notsupported
echo ============================================================================&echo.&echo Sorry! Your version is not supported.&echo.
:halt
pause >nul
